name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.4.2']

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install system dependencies
        run: |
          brew install gcc

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "rmarkdown", "knitr"))
          remotes::install_deps(dependencies = TRUE)
          if (!requireNamespace("randomForest", quietly = TRUE)) {
            install.packages("randomForest")
          }
        shell: Rscript {0}

      - name: Install Pandoc
        run: |
          brew install pandoc

      - name: Debug installed packages
        run: |
          installed.packages()[, c("Package", "Version")]
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-build-vignettes", "--no-manual"), error_on = "error")
        shell: Rscript {0}
